# Generated by Django 4.2.15 on 2024-08-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
